package net.rushashki.shashki64.share.resources.images;

import com.google.gwt.resources.client.ClientBundle;
import com.google.gwt.resources.client.ImageResource;

/**
 * Auto Generated by mk_images.rb on Fri Nov 30 22:39:12 -0500 2012
 */
public interface Images extends ClientBundle {
  @Source("img/online.png")
  public ImageResource onlineIconImage();

  @Source("img/offline.png")
  public ImageResource offlineIconImage();

  @Source("img/playing.png")
  public ImageResource playingIconImage();

  @Source("img/busy.gif")
  public ImageResource busyIconImage();

  @Source("img/vk.png")
  public ImageResource vkontakteIconImage();

  @Source("img/facebook.png")
  public ImageResource facebookIconImage();

  @Source("img/google.png")
  public ImageResource googleIconImage();

  @Source("img/yahoo.png")
  public ImageResource yahooIconImage();

  @Source("img/live32.png")
  public ImageResource liveIconImage();

  @Source("img/close.png")
  public ImageResource closeIconImage();

  @Source("img/loading.gif")
  public ImageResource loadIconImage();

  @Source("img/login_pointer.png")
  public ImageResource loginPointerIconImage();
}
